---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: day2-as-sno-9
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/jortega029/workshop-gitops-content-deploy.git
      revision: sno-9-setup
      files:
      - path: "config-definition/**/config.json" 
  template:
    metadata:
      name: 'sno-9-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/jortega029/helm-infra-gitops-workshop.git
        targetRevision: sno-9
        path: .
        helm:
          valueFiles:
            - '{{valuesFile}}'        
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: openshift-gitops
      syncPolicy:
        automated:
          prune: true
          selfHeal: true 
