---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: day2-as-sno-<name>
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/<your_user>/workshop-gitops-content-deploy.git
      revision: sno-<name>-setup
      files:
      - path: "config-definition/**/config.json" 
  template:
    metadata:
      name: 'sno-<name>-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/<your_user>/helm-infra-gitops-workshop.git
        targetRevision: sno-<name>
        path: .
        helm:
          valueFiles:
            - '{{valuesFile}}'        
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: openshift-gitops
      syncPolicy:
        automated:
          prune: true
          selfHeal: true 